services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-admin-client
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
    command: npm run dev -- --host
